version: "3"
services:
  neji-pfe:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=neji
      - MONGO_PASSWORD=neji

    command: sh -c "npm install -g mocha &&
             npm install &&
              npm run test"
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neji
      - MONGO_INITDB_ROOT_PASSWORD=neji