version: "3"
services:
  neji-pfe:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT= 3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=neji
      - MONGO_INITDB_ROOT_PASSWORD=neji
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
